<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Model\IconList;

?>
<?= $this->doctype() ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/app.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>

        <div class="container">
            <header class="brand-header py-3">
                <div class="row flex-nowrap justify-content-between align-items-center">
                    <div class="col-4 pt-1">
                        <?= date('l, j F, Y'); ?>
                    </div>
                    <?php $newAuthService = new \Laminas\Authentication\AuthenticationService();
                    if (!$newAuthService->hasIdentity()){ ?>
                        <div class="logo col-4 text-center">
                        <a href="<?= $this->url('home'); ?>">MyApp</a>
                    </div>

                    <div class="col-4 d-flex justify-content-end align-items-center">
                        <a href="#" class="btn btn-sm btn-outline-secondary mr-2">Авторизация</a>

                        <a href="#" class="btn btn-sm btn-outline-secondary">Регистрация</a>
                    </div>
                    <?php } else { ?>
                    <div class="col-4 d-flex justify-content-end align-items-center">
                        <a href="#" class="btn btn-sm btn-outline-secondary mr-2"><i class="<?php echo IconList::SIGN_OUT ?>"></i></a>
                    </div>
                    <?php } ?>
                </div>
            </header>

            <div class="appNav py-1 mb-2">
                <nav class="nav d-flex">
                    <a href="#" class="pt-2 text-muted mr-2">Домашняя</a>
                    <a href="#" class="pt-2 text-muted">Участники</a>
                </nav>
            </div>
        </div>

        <main class="container" role="main">
            <?= $this->partial('partial/flash.phtml', $this->flashMessenger()); ?>
            <?= $this->content ?>
            <hr>
        </main>


        <footer class="text-center text-muted">
            <div class="small">
                <p class="mb-1">
                    <?= $this->translate('Copyright &copy; ' . date('Y') . '. Все права защищены.'); ?>
                </p>
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a href="#">Privacy</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">Terms</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </footer>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
    <script src="https://kit.fontawesome.com/50a83f7ec3.js" crossorigin="anonymous"></script>
</html>
