<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Страница</h1>

    <p>
        Текст
    </p>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="#">Страница &raquo;</a>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Страница 1</h2>
        <div class="card-body">
            <p>
                Текст
            </p>

            <a class="btn btn-primary" href="#">Страница 1 &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Страница 2</h2>
        <div class="card-body">
            <p>
                Текст
            </p>

            <a class="btn btn-primary" href="#">Страница 2 &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Страница 3</h2>
        <div class="card-body">
            <p>
                Текст
            </p>

            <a class="btn btn-primary" href="#">Страница 3 &raquo;</a>
        </div>
    </div>
</div>
